version: '3.8'

services:
  vestas-stock-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vestas-stock-api
    ports:
      - "8000:8000" #api server
      - "8501:8501" #streamlit app
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./reports:/app/reports
      - ./results:/app/results
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 