version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./models/figures:/app/models/figures
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    environment:
      - ENVIRONMENT=production
    networks:
      - mlops-network

  streamlit:
    build:
      context: .
      dockerfile: ./deployment/Dockerfile.streamlit
    ports:
      - "8501:8501"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./models/figures:/app/models/figures
    depends_on:
      - api
    environment:
      - API_URL=http://api:8000
    networks:
      - mlops-network

  monitoring:
    build:
      context: .
      dockerfile: ./deployment/Dockerfile.monitoring
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./models/figures:/app/models/figures
    depends_on:
      - api
    environment:
      - ENVIRONMENT=production
    restart: unless-stopped
    networks:
      - mlops-network

networks:
  mlops-network:
    driver: bridge 