name: Build Docker Image

on:
  push:
    branches: [ docker ]
  pull_request:
    branches: [ docker ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: mlops-exam:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max 